services:
  - type: web
    name: okc-trash-api
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    domains:
      - okc-trash-api.onrender.com
